app/filings/models.py
from app import db
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm.exc import NoResultFound


class Company(db.Model):
    __tablename__ = 'companies'
    __table_args__ = {'schema': 'secfilings'}

    id = db.Column(db.Integer, primary_key=True)
    company_cik = db.Column(db.Integer)
    company_name = db.Column(db.String(150))
    num_filings = db.Column(db.Integer)

    def __init__(self, company_cik, **kwargs):
        self.company_cik = company_cik
        self.add_filings(kwargs.get('temp_files', None))

    def __repr__(self):
        return '<Company CIK: {} - Company Name: {}>'.format(self.company_cik, self.company_name)

    @property
    def title_name(self):
        return self.company_name.title()

    @property
    def zeros_cik(self):
        return str(self.company_cik).zfill(10)

    @property
    def upper_case_name(self):
        return self.company_name.upper()

    @property
    def serialize(self):
        return dict(company_id=self.id,
                    company_cik=self.zeros_cik,
                    company_name=self.title_name,
                    num_filings=self.num_filings)

    @hybrid_property
    def get_company_name(self):
        if not hasattr(self, "alternate_names"):
            return "No company name has been associated with this CIK"
        return self.alternate_names.order_by(Altname.last_filing.desc()).first().company_name

    @hybrid_property
    def set_name(self):
        self.company_name = self.get_company_name

    @hybrid_property
    def get_num_filings(self):
        return sum((i.num_filings for i in self.alternate_names.all()))

    @hybrid_property
    def set_filings(self):
        self.num_filings = self.get_num_filings

    def add_filings(self, filings):
        import itertools
        for _name, _filings in itertools.groupby(filings, key=lambda f: f['Company Name']):
            _company = Altname.query.filter_by(company_name=_name, id=self.id).first()
            if _company is None:
                _company = Altname(_name)
                self.alternate_names.append(_company)
            _company.add_multiple(_filings)
            db.session.add(self)
        db.session.commit()


class Altname(db.Model):
    __tablename__ = 'altnames'
    __table_args__ = {'schema': 'secfilings'}
    id = db.Column(db.Integer, primary_key=True)
    company_name = db.Column(db.String(150))
    first_filing = db.Column(db.Date)
    last_filing = db.Column(db.Date)
    num_filings = db.Column(db.Integer)

    company_id = db.Column(db.Integer, db.ForeignKey(Company.id, schema='secfilings'))
    company = db.relationship("Company", backref=db.backref('alternate_names', lazy='dynamic'))

    def __init__(self, company_name, first_filing=None, last_filing=None, num_filings=0):
        self.company_name = company_name
        self.first_filing = first_filing
        self.last_filing = last_filing
        self.num_filings = num_filings

    def __repr__(self):
        return '<Company {}>'.format(self.company_name)

    @property
    def serialize(self):
        return dict(company_id=self.company.id,
                    altname_id=self.id,
                    company_name=self.company_name.title(),
                    first_filing=self.first_filing.isoformat(),
                    last_filing=self.last_filing.isoformat(),
                    num_filings=self.num_filings,
                    company_cik=self.company.zeros_cik,
                    updated_name=self.company.title_name)

    def add_filing(self, filing):
        if filing not in self.company.filings:
            self.num_filings += 1
            self.company.num_filings += 1
            self.company.filings.append(filing)

    def add_multiple(self, filings):
        for temp in filings:
            if not (self.first_filing <= temp['Date Filed'] <= self.last_filing):
                continue
            filing = Filing(temp['Form Type'], temp['Date Filed'], 'ftp://ftp.sec.gov/' + temp['Filename'])
            form = Forms.query.filter_by(form_type=filing.form_type).first()
            if form is not None:
                form.add_form()
            else:
                form = Forms(filing.form_type)
            filing.form_id = form.id
            self.add_filing(filing)

    @property
    def update_date(self, commit=True):
        self.first_filing = min(self.company.filings, key=lambda g: g.filing_date).filing_date
        self.last_filing = max(self.company.filings, key=lambda g: g.filing_date).filing_date
        if commit:
            db.session.add(self)
            db.session.commit()


class Forms(db.Model):
    __tablename__ = 'formtypes'
    __table_args__ = {'schema': 'secfilings'}

    id = db.Column(db.Integer, primary_key=True)

    form_type = db.Column(db.String(10))
    num_forms = db.Column(db.Integer)

    def __init__(self, form_type, num_forms=0):
        self.form_type = form_type
        self.num_forms = num_forms

    def __repr__(self):
        return '<Form type {!r}>'.format(self.form_type)

    @property
    def serialize(self):
        return dict(form_id=self.id,
                    form_type=self.form_type,
                    num_forms=self.num_forms)

    def add_form(self):
        self.num_forms += 1


class Filing(db.Model):
    __tablename__ = 'filings'
    __table_args__ = {'schema': 'secfilings'}

    id = db.Column(db.Integer, primary_key=True)
    form_type = db.Column(db.String(10))
    filing_date = db.Column(db.Date)
    filing_url = db.Column(db.String(70))
    company_id = db.Column(db.Integer, db.ForeignKey(Company.id, schema='secfilings'))
    company = db.relationship("Company", backref=db.backref('filings', lazy='dynamic'))

    form_id = db.Column(db.Integer, db.ForeignKey(Forms.id, schema='secfilings'))
    form = db.relationship("Forms", backref=db.backref('filings', lazy='dynamic'))

    def __init__(self, form_type, filing_date, filing_url):
        self.form_type = form_type
        self.filing_date = filing_date
        self.filing_url = filing_url

    def __repr__(self):
        return '<Filing {!r}>'.format(self.filing_url)

    @property
    def generator_stream(self):
        return ('"' + str(_var) + '"' for _var in (self.company.company_name, self.company.company_cik, self.filing_date,
                self.filing_url, self.form_type))

    @property
    def generator_csv(self):
        return {'Company Name': self.company.company_name,
                'CIK': self.company.company_cik,
                'Date Filed': self.filing_date,
                'Filename': self.filing_url,
                'Form Type': self.form_type}

    @property
    def serialize(self):
        return dict(filing_id=self.id,
                    company_id=self.company.id,
                    company_name=self.company.title_name,
                    company_cik=self.company.zeros_cik,
                    filing_date=self.filing_date.isoformat(),
                    filing_url=self.filing_url,
                    form_type=self.form_type)

app/filings/forms.py
from flask.ext.wtf.html5 import (
        SearchField, DateField, IntegerField,
        Form, SubmitField
        )


class SearchForm(Form):
    startdate = DateField("Start Date", format="%Y-%m-%d")
    enddate = DateField("End Date", format="%Y-%m-%d")
    company_cik = IntegerField("Company CIK")
    company_name = SearchField("Company Name")
    submit = SubmitField(label='Search')

app/filings/views.py
from flask import render_template, flash, redirect, request, url_for, session, g, Blueprint, jsonify
from .models import Company, Filing, Altname, Forms
from .constants import VIEWS_MAP
from app.users.models import User
from app import db

mod = Blueprint('filings', __name__, url_prefix='/filings')


@mod.before_request
def before_request():
    """
    pull user's profile from the database before every request are treated
    """
    g.user = None
    if 'user_id' in session and session['user_id'] is not None:
        g.user = User.query.get(session['user_id'])
        g.user_role = g.user.role


@mod.route('/companies/', defaults={'page': 1}, methods=("GET", "POST"))
@mod.route('/companies/<int:page>/')
def show_companies(page):

    _returnargs = process_request(request, 'companies', page=page)
    companies = _returnargs['storage']

    if companies is None:
        flash('Company not found.')

    return render_template('filings/companies.html',
                           title='Home',
                           companies=companies,
                           )


@mod.route('/_get_json')
def get_json():

    page = request.args.get('page', 1, type=int)
    caller = request.args.get('caller', 'filings')
    company_id = request.args.get('company_id', 1, type=int)
    form_id = request.args.get('form_id', 1, type=int)

    _returnargs = process_request(request,
                                  caller,
                                  page=page,
                                  company_id=company_id,
                                  form_id=form_id)

    mapped_items = [item.serialize for item in _returnargs['storage'].items]
    num_pages = _returnargs['storage'].pages
    del _returnargs['storage']

    return jsonify(
                    items=mapped_items,
                    num_pages=num_pages,
                    **_returnargs
                    )


@mod.route('/companies/company/<int:company_id>/', defaults={'page': 1}, methods=("GET", "POST"))
@mod.route('/companies/company/<int:company_id>/<int:page>/')
def show_entries(company_id, page):

    _returnargs = process_request(request, 'company', company_id, page)
    filings = _returnargs['storage']
    company = Company.query.get(company_id)
    if not (company and filings):
        flash('No filings found for company {}'.format(company_id))

    return render_template('filings/company.html',
                           title='Home',
                           company=company,
                           filings=filings
                           )


@mod.route('/forms/', defaults={'page': 1}, methods=("GET", "POST"))
@mod.route('/forms/<int:page>/')
def show_types(page):
    _returnargs = process_request(request, 'forms', page=page)
    forms = _returnargs['storage']

    if not forms:
        flash('No forms found')

    return render_template('filings/forms.html',
                         forms=forms
                         )


@mod.route('/forms/type/<int:form_id>/', defaults={'page': 1}, methods=("GET", "POST"))
@mod.route('/forms/type/<int:form_id>/<int:page>/')
def type_entries(form_id, page):
    form = Forms.query.get(form_id)
    _returnargs = process_request(request, 'form', form_id=form.id, page=page)
    filings = _returnargs['storage']

    if not filings:
        flash('No forms found of type {}'.format(form.form_type))

    return render_template('filings/form.html',
                           form=form,
                           filings=filings,
                           )


def save_entries(request, caller='company'):
    action = request.form.get('action')
    user = g.user

    if caller in ('company', 'form'):
        for filing in request.form.getlist('filing_check', type=int):
            c = Filing.query.get(filing)
            if action == "save":
                user.filings.append(c)
            elif action == "delete" and c in user.filings:
                user.filings.remove(c)

    elif caller == 'companies':
        companies = request.form.getlist('company_check')
        for company in companies:
            for filing in company.filings:
                c = Filing.query.get(filing)
                if action == "save":
                    user.filings.append(c)
                elif action == "delete" and c in user.filings:
                    user.filings.remove(c)

    elif caller == 'forms':
        for forms in request.form.getlist('form_check'):
            for filing in forms.filings:
                c = Filing.query.get(filing)
                if action == "save":
                    user.filings.append(c)
                elif action == "delete" and c in user.filings:
                    user.filings.remove(c)

    db.session.add(user)
    db.session.commit()
    print(user.filings, action)


def process_request(request, caller='company', company_id=None, page=1, form_id=None):

    if request.form.get('action', '') in ('save', 'delete'):
        save_entries(request, caller)

    defaults = VIEWS_MAP[caller]

    num_per_page = request.args.get('paginate', defaults['paginate'], type=int)
    num_per_page = 100 if num_per_page > 100 else num_per_page
    ordering = request.args.get('order', defaults['order'])
    _sort = request.args.get('sort_by', defaults['sort_param'])

    if ordering.startswith('asc'):
        sort_param = defaults['storage'][0][_sort]
    else:
        sort_param = defaults['storage'][0][_sort].desc()

    if caller == 'company':
        company = Company.query.get(company_id)
        storage = company.filings.order_by(sort_param).paginate(page, num_per_page, False)
        storage = Filing.query.filter_by(company_id=company_id).order_by(sort_param).paginate(page, num_per_page, False)

    elif caller == 'companies':
        storage = Company.query.order_by(sort_param).paginate(page, num_per_page, False)

    elif caller == 'form':
        storage = Filing.query.filter_by(form_id=form_id).join(Company).order_by(sort_param).paginate(page, num_per_page, False)

    elif caller == 'forms':
        storage = Forms.query.order_by(sort_param).paginate(page, num_per_page, False)

    elif caller == 'filings':
        storage = Filing.query.order_by(sort_param).paginate(page, num_per_page, False)

    else:
        storage = None

    return {
            'storage': storage,
            'page': page,
            'per_page': num_per_page,
            'order_by': _sort,
            'direction': ordering
            }

app/templates/filings/companies.html
{% extends "base.html" %}
{% from 'forms/macros.html' import render_pagination with context %}
{% from 'forms/macros.html' import render_header with context %}
{% from 'forms/macros.html' import submit_button with context %}
{% from 'forms/macros.html' import table_footer with context %}
{% set active_page = "companies" %}
{% block content %}
{% set filing_items = [
    ('company_cik', 'Company CIK'),
    ('company_name', 'Company Name'),
    ('num_filings', 'Number of filings')
] -%}
{% set data = request.args.to_dict() %}
<form name="favorite" action="." method="POST">
    <table class="table table-striped table-condensed table-hover">
    {{ render_header('filings.show_companies', filing_items, **data) }}
        <fieldset>
        {% for company in companies.items %}
          <tr>
            <td><div class="checkbox"><input type="checkbox" name="filing_check" value="{{ company.id }}"></div></td>
            <td>{{ (company.company_cik|string).zfill(10) }}</td>
            <td><a href="{{ url_for('filings.show_entries', company_id=company.id) }}"> {{ company.upper_case_name|title }}</a></td>
            <td>{{ company.num_filings }} </td>
          </tr>
        {% endfor %}
        </fieldset>
    </table>
    {{ submit_button() }}
</form>
    {{ table_footer('filings.show_companies', **data) }}
    {{ render_pagination(companies, 'filings.show_companies', **data) }}
{% endblock %}

app/templates/filings/company.html
{% extends "base.html" %}
{% from 'forms/macros.html' import render_pagination with context %}
{% from 'forms/macros.html' import render_header with context %}
{% from 'forms/macros.html' import submit_button with context %}
{% from 'forms/macros.html' import table_footer with context %}

{% block content %}
{% set company_items = [
    ('form_type', 'Form type'),
    ('filing_date', 'Filing date'),
    ('filing_url', 'Link')
] -%}
{% set data = request.args.to_dict() %}
{% do data.update(company_id=company.id) %}
    <h1><< Filings for {{ company.company_name|title }} | {{ company.company_cik }} >></h1>
    <form name="favorite" action="" method="POST">
    <table class="table table-condensed table-striped table-hover">
        {{ render_header('filings.show_entries', company_items, **data) }}
        <fieldset>
        {% for filing in filings.items %}
            <tr>
                <td><div class="checkbox"><input type="checkbox" name="filing_check" value="{{ filing.id }}"></div></td>

                <td><a href="{{ url_for('filings.show_types', form_id=filing.form_id) }}"> {{ filing.form_type|upper }}</a></td>
                <td>{{ filing.filing_date }}</td>
                <td><a href="{{ filing.filing_url }}">Link</a></td>
            </tr>
        {% endfor %}
        </fieldset>
    </table>
    {{ submit_button() }}
    </form>
    {{ table_footer('filings.show_entries', **data) }}
    {{ render_pagination(filings, 'filings.show_entries', **data) }}
{% endblock %}

app/templates/filings/form.html
{% extends "base.html" %}
{% from 'forms/macros.html' import render_pagination with context %}
{% from 'forms/macros.html' import render_header with context %}
{% from 'forms/macros.html' import submit_button with context %}
{% from 'forms/macros.html' import table_footer with context %}
{% set active_page = "forms" %}
{% block content %}
{% set filing_items = [
    ('company_name', 'Company Name'),
    ('filing_date', 'Filing Date'),
    ('filing_url', 'Link')
] -%}
{% set data = request.args.to_dict() %}
{% do data.update(form_id = form.id) %}
<form name="favorite" action="." method="POST">
    <table class="table table-striped table-condensed table-hover">
    {{ render_header('filings.type_entries', filing_items, **data) }}
        <fieldset>
        {% for filing in filings.items %}
          <tr>
            <td><div class="checkbox"><input type="checkbox" name="filing_check" value="{{ filing.id }}"></div></td>
            <td><a href="{{ url_for('filings.show_entries', company_id=filing.company_id) }}"> {{ filing.company.company_name|title }}</a></td>

            <td>{{ filing.filing_date }}</td>
            <td><a href="{{ filing.filing_url }}">Link</a></td>
          </tr>
        {% endfor %}
        </fieldset>
    </table>
    {{ submit_button() }}
</form>
    {{ table_footer('filings.type_entries', **data)}}
    {{ render_pagination(filings, 'filings.type_entries', **data) }}
{% endblock %}

app/templates/filings/forms.html
{% extends "base.html" %}
{% from 'forms/macros.html' import render_pagination with context %}
{% from 'forms/macros.html' import render_header with context %}
{% from 'forms/macros.html' import submit_button with context %}
{% from 'forms/macros.html' import table_footer with context %}
{% set active_page = "forms" %}
{% block content %}
{% set filing_items = [
    ('form_type', 'Form Type'),
    ('num_forms', 'Number of filings')
] -%}
{% set data = request.args.to_dict() %}
<form name="favorite" action="." method="POST">
    <table class="table table-striped table-condensed table-hover">
        {{ render_header('filings.show_types', filing_items, **data) }}
        <fieldset>
        {% for form in forms.items %}
          <tr>
            <td><div class="checkbox"><input type="checkbox" name="form_check" value="{{ form.id }}"></div></td>
            <td><a href="{{ url_for('filings.type_entries', form_id=form.id) }}"> {{ form.form_type|upper }}</a></td>
            <td>{{ form.num_forms }} </td>
          </tr>
        {% endfor %}
        </fieldset>
    </table>
    {{ submit_button() }}
</form>
    {{ table_footer('filings.show_types', **data) }}
    {{ render_pagination(forms, 'filings.show_types', **data) }}
{% endblock %}