app/filings/views.py
from flask import render_template, flash, redirect, request, url_for, session, g, Blueprint, jsonify
from .models import Company, Filing, Altname, Forms
from .constants import VIEWS_MAP
from app.users.models import User
from app import db

mod = Blueprint('filings', __name__, url_prefix='/filings')


@mod.before_request
def before_request():
    """
    pull user's profile from the database before every request are treated
    """
    g.user = None
    if 'user_id' in session and session['user_id'] is not None:
        g.user = User.query.get(session['user_id'])
        g.user_role = g.user.role


@mod.route('/companies/', defaults={'page': 1}, methods=("GET", "POST"))
@mod.route('/companies/<int:page>/')
def show_companies(page):

    _returnargs = process_request(request, 'companies', page=page)
    companies = _returnargs['storage']

    if companies is None:
        flash('Company not found.')

    return render_template('filings/companies.html',
                           title='Home',
                           companies=companies,
                           )


@mod.route('/_get_json')
def get_json():

    page = request.args.get('page', 1, type=int)
    caller = request.args.get('caller', 'filings')
    company_id = request.args.get('company_id', 1, type=int)
    form_id = request.args.get('form_id', 1, type=int)

    _returnargs = process_request(request,
                                  caller,
                                  page=page,
                                  company_id=company_id,
                                  form_id=form_id)

    mapped_items = [item.serialize for item in _returnargs['storage'].items]
    num_pages = _returnargs['storage'].pages
    del _returnargs['storage']

    return jsonify(
                    items=mapped_items,
                    num_pages=num_pages,
                    **_returnargs
                    )


@mod.route('/companies/company/<int:company_id>/', defaults={'page': 1}, methods=("GET", "POST"))
@mod.route('/companies/company/<int:company_id>/<int:page>/')
def show_entries(company_id, page):

    _returnargs = process_request(request, 'company', company_id, page)
    filings = _returnargs['storage']
    company = Company.query.get(company_id)
    if not (company and filings):
        flash('No filings found for company {}'.format(company_id))

    return render_template('filings/company.html',
                           title='Home',
                           company=company,
                           filings=filings
                           )


@mod.route('/forms/', defaults={'page': 1}, methods=("GET", "POST"))
@mod.route('/forms/<int:page>/')
def show_types(page):
    _returnargs = process_request(request, 'forms', page=page)
    forms = _returnargs['storage']

    if not forms:
        flash('No forms found')

    return render_template('filings/forms.html',
                         forms=forms
                         )


@mod.route('/forms/type/<int:form_id>/', defaults={'page': 1}, methods=("GET", "POST"))
@mod.route('/forms/type/<int:form_id>/<int:page>/')
def type_entries(form_id, page):
    form = Forms.query.get(form_id)
    _returnargs = process_request(request, 'form', form_id=form.id, page=page)
    filings = _returnargs['storage']

    if not filings:
        flash('No forms found of type {}'.format(form.form_type))

    return render_template('filings/form.html',
                           form=form,
                           filings=filings,
                           )


def save_entries(request, caller='company'):
    action = request.form.get('action')
    user = g.user

    if caller in ('company', 'form'):
        for filing in request.form.getlist('filing_check', type=int):
            c = Filing.query.get(filing)
            if action == "save":
                user.filings.append(c)
            elif action == "delete" and c in user.filings:
                user.filings.remove(c)

    elif caller == 'companies':
        companies = request.form.getlist('company_check')
        for company in companies:
            for filing in company.filings:
                c = Filing.query.get(filing)
                if action == "save":
                    user.filings.append(c)
                elif action == "delete" and c in user.filings:
                    user.filings.remove(c)

    elif caller == 'forms':
        for forms in request.form.getlist('form_check'):
            for filing in forms.filings:
                c = Filing.query.get(filing)
                if action == "save":
                    user.filings.append(c)
                elif action == "delete" and c in user.filings:
                    user.filings.remove(c)

    db.session.add(user)
    db.session.commit()
    print(user.filings, action)


def process_request(request, caller='company', company_id=None, page=1, form_id=None):

    if request.form.get('action', '') in ('save', 'delete'):
        save_entries(request, caller)

    defaults = VIEWS_MAP[caller]

    num_per_page = request.args.get('paginate', defaults['paginate'], type=int)
    num_per_page = 100 if num_per_page > 100 else num_per_page
    ordering = request.args.get('order', defaults['order'])
    _sort = request.args.get('sort_by', defaults['sort_param'])

    if ordering.startswith('asc'):
        sort_param = defaults['storage'][0][_sort]
    else:
        sort_param = defaults['storage'][0][_sort].desc()

    if caller == 'company':
        company = Company.query.get(company_id)
        storage = company.filings.order_by(sort_param).paginate(page, num_per_page, False)
        storage = Filing.query.filter_by(company_id=company_id).order_by(sort_param).paginate(page, num_per_page, False)

    elif caller == 'companies':
        storage = Company.query.order_by(sort_param).paginate(page, num_per_page, False)

    elif caller == 'form':
        storage = Filing.query.filter_by(form_id=form_id).join(Company).order_by(sort_param).paginate(page, num_per_page, False)

    elif caller == 'forms':
        storage = Forms.query.order_by(sort_param).paginate(page, num_per_page, False)

    elif caller == 'filings':
        storage = Filing.query.order_by(sort_param).paginate(page, num_per_page, False)

    else:
        storage = None

    return {
            'storage': storage,
            'page': page,
            'per_page': num_per_page,
            'order_by': _sort,
            'direction': ordering
            }

app/users/views.py
from flask import (Blueprint, request, render_template,
                   flash, g, session, redirect, url_for,
                   Response, send_file)
from werkzeug import check_password_hash, generate_password_hash
import itertools
import datetime

from app import db

from app.users.forms import RegisterForm, LoginForm, UserForm
from app.users.models import User
from app.users.decorators import requires_login, requires_admin

from app.filings.models import Company, Filing

mod = Blueprint('users', __name__)


@mod.route('/')
@mod.route('/index')
def index():
    limit = request.args.get('limit', 25)
    filings = Filing.query.order_by(Filing.filing_date.desc()).limit(limit)

    return render_template("index.html",
                           title='Home',
                           filings=filings,
                           limit=limit
                           )


@mod.route('/users/')
@requires_login
def home():
    user = g.user
    user_filings = dict((k, list(v)) for k, v in itertools.groupby(user.filings, key=lambda f: f.company.company_name))
    return render_template("users/profile.html", user=user, filings=user_filings)


@mod.before_request
def before_request():
    """
    pull user's profile from the database before every request are treated
    """
    g.user = None
    if 'user_id' in session and session['user_id'] is not None:
        g.user = User.query.get(session['user_id'])
        g.user_role = g.user.role


@mod.route('/users/login/', methods=['GET', 'POST'])
def login():
    """
    Login form
    """
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
            # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed,
            # it's a safe place to store the user id
            session['user_id'] = user.id
            session['user_role'] = user.role
            flash('Welcome %s' % user.name)
            return redirect(url_for('users.home'))
        flash('Wrong email or password', 'error-message')
    return render_template("users/login.html", form=form)


@mod.route('/users/logout/', methods=["GET", "POST"])
def logout():
    """
    Logout form
    """
    session.pop('user_id', None)
    session.pop('user_role', None)
    return redirect(url_for('filings.index'))


@mod.route('/users/register/', methods=['GET', 'POST'])
def register():
    """
    Registration Form
    """
    form = RegisterForm(request.form)
    if form.validate_on_submit():
      # create an user instance not yet stored in the database
        user = User(name=form.name.data, email=form.email.data,
            password=generate_password_hash(form.password.data))
      # Insert the record in our database and commit it
        db.session.add(user)
        db.session.commit()

      # Log the user in, as he now has an id
        session['user_id'] = user.id

      # flash will display a message to the user
        flash('Thanks for registering')
      # redirect user to the 'home' method of the user module.
        return redirect(url_for('users.home'))
    return render_template("users/register.html", form=form)


@mod.route('/admin/')
@requires_admin
def admin_index():
    return render_template('admin/index.html')


@mod.route('/admin/users/', methods=["GET"])
@requires_admin
def admin_users():
    users = User.query.all()
    return render_template('admin/users.html', users=users)


@mod.route('/admin/users/edit', defaults={'user': 1})
@mod.route('/admin/users/edit/<int:user>', methods=['GET', 'POST'])
@requires_admin
def edit_users(user):
    user = User.query.get(user)
    form = UserForm(request.form, obj=user)
    if form.validate_on_submit():
        user.role = form.role.data
        db.session.add(user)
        db.session.commit()
        flash('Successfully updated {} to role {}'.format(user.name, user.role))
    return render_template('admin/edit_users.html', form=form)


@mod.route('/admin/companies/', defaults={'page': 1})
@mod.route('/admin/companies/<int:page>')
@requires_admin
def admin_view(page):
    companies = Company.query.order_by(Company.num_filings.desc()).paginate(page, 20, False)

    return render_template('admin/companies.html',
                           title='Admin',
                           companies=companies
                           )


@mod.route('/users/file/', methods=("GET", "POST"))
@requires_login
def generate_filings():
    if request.form.get('action', '') in ('download', 'delete'):
        return do_filings(request)
    return redirect(url_for('users.home'))


def do_filings(request):
    import tempfile
    import csv
    action = request.form.get('action')
    user = g.user
    filings = [Filing.query.get(i) for i in request.form.getlist('filing_check', type=int)] or user.filings

    if action == "download":
        attachment_filename = request.form.get('filename', 'edgar_filings_{}.csv'.format(datetime.date.today().strftime('%m_%d_%y')))
        tf = tempfile.NamedTemporaryFile(mode="w+", newline='', delete=False)
        temp_csv = csv.writer(tf, csv.QUOTE_ALL)
        temp_csv.writerow(('Company Name', 'Company CIK', 'Filing Date', 'Filing URL', 'Form Type'))
        for filing in filings:
            print(filing.generator_csv)
            temp_csv.writerow(filing.generator_csv)
        tf.close()
        tf2 = open(tf.name, 'rb')
        return send_file(tf2, as_attachment=True,
                attachment_filename=attachment_filename)

    elif action == 'delete':
        for filing in filings:
            c = Filing.query.get(filing)
            if c in user.filings:
                user.filings.remove(c)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.home'))

app/templates/base.html
<html lang="en">
<head>

{% set navigation_bar = [
  ("users.index", "index", "Index"),
  ("filings.show_companies", "companies", "Companies"),
  ("users.home", "users", "Profile"),
  ("filings.show_types", "forms", "Forms"),
] -%}

{% set nav_menu = [
  ("filings.show_companies", "companies", "Companies"),
  ("filings.show_types", "forms", "Forms"),
] -%}

{% if session.user_role == 0 %}

  {% set navigation_bar = [
    ("users.index", "index", "Index"),
    ("users.home", "users", "Profile"),
    ("users.admin_index", "admin", "Admin")
  ] -%}
  {% set admin_nav = [
    ("users.index", "index", "Home"),
    ("users.admin_index", 'admin', "Admin"),
    ('users.admin_users','admin_users', 'Edit Users'),
    ('users.admin_view', 'admin_companies', 'Edit Companies'),
    ('users.index','admin_filings', 'Edit Filings')
  ] -%}
  {% set active_side = active_side|default("admin") -%}

{% endif %}

{% set active_page = active_page|default("index") -%}
  {% block head %}
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='bs3/css/bootstrap.css') }}">
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='bs3/css/bootstrap-theme.css') }}">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">
  {% endblock %}
</head>
<body>

    <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
        <a class="navbar-brand" href="/index">Edgar SEC filings</a>
        <a class="navbar-toggle"
                data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="glyphicon glyphicon-bar"></span>
        <span class="glyphicon glyphicon-bar"></span>
        <span class="glyphicon glyphicon-bar"></span>
        </a>
    </div>
    <div class="container">
      <div class="navbar-collapse collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          {% for href, id, caption in navigation_bar %}
            <li {% if id == active_page %} class="active" {% endif %}>
                <a href="{{ url_for(href) }}">{{ caption|e }}</a></li>
          {% endfor %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Filings <b class="caret"></b></a>
            <ul class="dropdown-menu">
                {% for href, id, caption in nav_menu %}
                    <li><a href="{{ url_for(href) }}">{{ caption|e }}</a></li>
                {% endfor %}
            </ul>
          </li>
        </ul>

        <div style="display:inline-block" class="pull-right">
          <form class="navbar-form navbar-left" action="" role="search">
            <div class="form-group">
            <input type="text" class="search-query" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default navbar-btn"><span class="icon-search"></span></button>

          </form>
          <ul class="nav nav-tabs pull-right navbar-nav">
            <li class="divider-vertical"></li>
            {% if session.user_id %}
            <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="/users/">Profile<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('users.home') }}">Profile</a></li>
                <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
              </ul>
              </li>
            {% else %}
              <li><a href="{{ url_for('users.login') }}">Login</a></li>
            {% endif %}
          </ul>
        </div>
        </div><!--/.nav-collapse -->
      </div><!--container -->
    </div><!--navbar-inner -->
  </div><!--navbar navbar-fixed -->

  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <div class="nav nav-tabs nav-stacked navbar-collapse">
          <ul class="nav">
            {% for href, id, caption in admin_nav %}
              <li {% if id == active_side %} class="active" {% endif %}>
              <a href="{{ url_for(href) }}">{{ caption|e }}</a></li>
            {% endfor %}
          </ul>
        </div><!--nav-tabs-->
      </div>
      <div class="col-md-10">
        {% block content %}
        {% endblock %}
      </div>
    </div>

    <hr>

    {% block footer %}

    <footer class="footer">
      <p>&copy; Company 2012</p>
    </footer>
    {% endblock %}
  </div><!--container -->
  <script src="http://code.jquery.com/jquery.js"></script>
  <script src="{{url_for ('static', filename='bs3/js/bootstrap.js') }}"></script>
  <script src="{{url_for ('static', filename='js/knockout-2.3.0.debug.js') }}"></script>
  <script src="{{url_for ('static', filename='js/filings.js') }}"></script>
  <script src="http://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.js"></script>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Most recent {{limit}} filings</h1>
    <table class="table table-condensed table-striped">
    <tr>
        <th>Save</th><th>Company name</th><th>Form type</th><th>Date</th>
    </tr>
    {% for filing in filings %}
        <tr>
        <td><div class="checkbox"><input type="checkbox" name="filing_check" value="{{ filing.id }}"></div></td>
        <td><a href="{{ url_for('filings.show_entries', company_id=filing.company_id) }}">{{ filing.company.company_name|title }}</a></td>
        <td><a href="{{ url_for('filings.type_entries', form_id=filing.form_id) }}">{{ filing.form_type|upper }}</a></td>
        <td><a href="{{ filing.filing_url }}"> {{ filing.filing_date }}</td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}